version: "3.8"
services:
    # Mysql database container
    db:
        image: mysql
        container_name: db_symfony
        restart: always
        ports:
            - 3306:3306
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - tutorial

    # phpmyadmin container
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - tutorial

    # Symfony apache project container
    www:
        build: docker/php
        container_name: symfony
        ports:
          - "8741:80"
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - tutorial
            
    front:
        build:
            context: ./front/flame-funds-front
            dockerfile: Dockerfile
        container_name: vue
        ports:
            - 8000:8080
        restart: always
        networks:
            - tutorial
        volumes:
            - ./front/flame-funds-front/:/app
            - '/app/node_modules'
            
networks:
    tutorial:

volumes:
    db-data:
