<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerISGoLUu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerISGoLUu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerISGoLUu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerISGoLUu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerISGoLUu\App_KernelDevDebugContainer([
    'container.build_hash' => 'ISGoLUu',
    'container.build_id' => '99e3a29b',
    'container.build_time' => 1691187113,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerISGoLUu');
